import { getDbClient, runQuery } from "./dal";

async function initDbSchema() {
  const ddl = `
    BEGIN;

    CREATE TABLE IF NOT EXISTS new_user (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name TEXT NOT NULL,
      last_name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      isAdmin BOOLEAN NOT NULL DEFAULT FALSE
    );

    CREATE TABLE IF NOT EXISTS vacations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      destination TEXT NOT NULL,
      description TEXT NOT NULL,
      start_date TIMESTAMPTZ NOT NULL DEFAULT now(),
      end_date TIMESTAMPTZ NOT NULL DEFAULT now(),
      price NUMERIC(12,2) NOT NULL CHECK (price > 0),
      image_fileName TEXT NOT NULL 
    );

    CREATE TABLE IF NOT EXISTS followers (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL,
      vacation_id BIGINT NOT NULL,
      CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES new_user(id) ON DELETE RESTRICT,
      CONSTRAINT fk_vacation_id FOREIGN KEY (vacation_id) REFERENCES vacations(id) ON DELETE RESTRICT,
      UNIQUE(user_id, vacation_id)
    );

    CREATE INDEX IF NOT EXISTS idx_vacations_destination ON vacations(destination);
    CREATE INDEX IF NOT EXISTS idx_vacations_start_date ON vacations(start_date);
    CREATE INDEX IF NOT EXISTS idx_vacations_end_date ON vacations(end_date);

    CREATE INDEX IF NOT EXISTS idx_followers_user_id ON followers(user_id);
    CREATE INDEX IF NOT EXISTS idx_followers_vacation_id ON followers(vacation_id);

    COMMIT;
  `;
  await runQuery(ddl, [], undefined);
}

async function generateSampleData() {
  const dbClient = await getDbClient();
  try {
    await runQuery("BEGIN;", [], dbClient);
    await runQuery(`
      INSERT INTO vacations (destination, description, start_date, end_date, price, image_fileName)
      VALUES
      ('Paris, France', 'Romantic getaway in the city of lights', '2025-12-10', '2025-12-17', 1299.99, 'paris.jpg'),
      ('Rome, Italy', 'Explore ancient ruins and Italian cuisine', '2026-01-05', '2026-01-12', 1149.50, 'rome.jpg'),
      ('Barcelona, Spain', 'Beach, tapas, and Gaudí architecture', '2026-02-15', '2026-02-22', 999.00, 'barcelona.jpg'),
      ('New York City, USA', 'Winter shopping and Broadway shows', '2025-12-20', '2025-12-27', 1390.00, 'nyc.jpg'),
      ('Tokyo, Japan', 'Cherry blossoms and sushi adventures', '2026-03-25', '2026-04-02', 1899.99, 'tokyo.jpg'),
      ('Cape Town, South Africa', 'Safari and coastal beauty', '2026-01-10', '2026-01-20', 1490.00, 'capetown.jpg'),
      ('Reykjavik, Iceland', 'Northern lights and hot springs', '2026-02-01', '2026-02-08', 1695.00, 'iceland.jpg'),
      ('Bangkok, Thailand', 'Street food and floating markets', '2026-03-01', '2026-03-10', 899.00, 'bangkok.jpg'),
      ('Sydney, Australia', 'Opera House and Bondi Beach', '2026-01-15', '2026-01-25', 1790.00, 'sydney.jpg'),
      ('Rio de Janeiro, Brazil', 'Carnival and Copacabana fun', '2026-02-20', '2026-02-28', 1599.00, 'rio.jpg'),
      ('Amsterdam, Netherlands', 'Canals, bikes, and tulips', '2026-04-10', '2026-04-17', 1090.00, 'amsterdam.jpg'),
      ('Prague, Czech Republic', 'Fairytale city with rich history', '2026-03-05', '2026-03-12', 950.00, 'prague.jpg'),
      ('Dubai, UAE', 'Luxury shopping and desert safaris', '2026-01-20', '2026-01-27', 1399.00, 'dubai.jpg'),
      ('Athens, Greece', 'Mythology and Mediterranean sun', '2026-04-01', '2026-04-08', 999.00, 'athens.jpg'),
      ('Zanzibar, Tanzania', 'Tropical paradise with turquoise waters', '2026-02-10', '2026-02-18', 1290.00, 'zanzibar.jpg');
    `, [], dbClient);
    await runQuery("COMMIT;", [], dbClient);
  } catch (error) {
    await runQuery("ROLLBACK;", [], dbClient);
    throw error;
  } finally {
    dbClient.release();
  }
}

async function main() {
  await initDbSchema();
  await generateSampleData();
  console.log("Done init DB");
}

main().catch(err => {
  console.error("DB init failed:", err);
});

